name: Deploy React Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [17.5.0]
    
    steps:
      - name: Checking the repository code to gain access to it
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build React-app
        run: npm run build
      
      - name: Commit build folder
        run: git remote set-url origin https://git:${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git & git add -f build & git commit -m "Build update" & git push
      
      - name: Push build folder to gh-pages branch
        run: git push


