name: Deploy React Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [17.5.0]
    
    steps:
      - name: Checking the repository code to gain access to it
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build React-app
        run: npm run build
      
      - name: Commit build folder
        run: git checkout -b gh-pages | git commit ./build -m "Build update"
      
      - name: Push build folder to gh-pages branch
        run: git push


